Revert "km: test: convert to parameterized test"
This reverts commit ff6500c1244eba54ca3cb19df57dd70deb0ee164.

When building with:
m KMGK_gtest

We see:
error: unknown type name 'GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST'

parameterized tests are not supported in
external/googletest version android-11.0.0_r40.

Since KMGK_gtest is also part of VTS, this also breaks VTS rebuild.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>