Revert "km: test: fix encoding of device_locked field"
This reverts commit 6d7fd1d04fa4e130ccef3913995ea6c285e6a7c1.

When building with:
m KMGK_gtest

We see:
error: unknown type name 'GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST'

parameterized tests are not supported in
external/googletest version android-11.0.0_r40.

Since KMGK_gtest is also part of VTS, this also breaks VTS rebuild.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>