Revert "km: test: add initial check for SetUp()"
This reverts commit cfe2977c1f44db14c4cf2d3bcf2991171ba5331d.

When building with:
m KMGK_gtest

We see:
error: unknown type name 'GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST'

parameterized tests are not supported in
external/googletest version android-11.0.0_r40.

Since KMGK_gtest is also part of VTS, this also breaks VTS rebuild.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>